<?php
$key = "8a57f2b161aa7f876295561ddc72607f";
$token = "9b9a45c50344a79aa50ee90eba9aa50eea8cca0b6877df738903725d6a3d5875";
?>
<script>
    require([
        "jquery"
    ], function($){
//        var key="<?php //echo $key; ?>//";
//        var token="<?php //echo $token; ?>//";
//        var cartUrl = "https://api.trello.com/1/members/venugopal47/boards?key=8a57f2b161aa7f876295561ddc72607f&token=9b9a45c50344a79aa50ee90eba9aa50eea8cca0b6877df738903725d6a3d5875";
//        $.ajax({
//            dataType: "json",
//            method: "GET",
//            url: cartUrl,
//            success:function (data) {
//                //var response = $.parseJSON(data);
//                console.log(data);
//            }
//        });
    });
</script>
<script>
//    require([
//        "jquery"
//    ], function($){
//        var key="<?php //echo $key; ?>//";
//        var token="<?php //echo $token; ?>//";
//        var name="Testing Board";
//        var cartUrl = "https://api.trello.com/1/boards?key=8a57f2b161aa7f876295561ddc72607f&token=9b9a45c50344a79aa50ee90eba9aa50eea8cca0b6877df738903725d6a3d5875";
//        $.ajax({
//            dataType: "json",
//            method: "POST",
//            url: cartUrl,
//            data:{name: name},
//            success:function (data) {
//                //var response = $.parseJSON(data);
//                console.log(data);
//            }
//        });
//    });
</script>
<script>
//    require([
//        "jquery"
//    ], function($){
//        var key="<?php //echo $key; ?>//";
//        var token="<?php //echo $token; ?>//";
//        var name="Testing Board";
//        var cartUrl = "https://api.trello.com/1/boards?key=8a57f2b161aa7f876295561ddc72607f&token=9b9a45c50344a79aa50ee90eba9aa50eea8cca0b6877df738903725d6a3d5875";
//        $.ajax({
//            dataType: "json",
//            method: "POST",
//            url: cartUrl,
//            data:{name: name},
//            success:function (data) {
//                //var response = $.parseJSON(data);
//                console.log(data);
//            }
//        });
//    });
</script>
